### ISSUE TITLE
[EPIC] Editor guide: how to contribute content and datasets

### ISSUE THREAD

**Issue by rufuspollock** [datopian/makeitmarkdown#1]
Create a first editor guide for adding and editing conten to a **markdown-based** site -- specifically a markdown-based, flowershow-published site and even more specifically a "MOGF" (markdown-obsidian-github-flowershow built site).

## Outcome visioning 🎯 (High level acceptance)

A non-dev editor/author at Life Itself or anywhere else has a **single** online place to go to with (or linking to) **sufficient docs** to **autonomously** (i.e. without dev support) ...

- [ ] Edit lifeitself.org
  - [ ] Create a new blog post
  - [ ] Create a new page
  - [ ] Edit a blog post or page
- [ ] Create, share and publish a micro-catalog
  - [ ] Create locally
  - [ ] Share with others (privately)
  - [ ] Publish
- [ ] Create a digital knowledge garden i.e. content + catalogs etc

### Prep

```[tasklist]
- [x] Merge in (and then close as duplicate) https://github.com/life-itself/community/issues/519 **✅2023-05-24**
- [x] Merge in and then close https://github.com/orgs/life-itself/discussions/393 **✅2023-05-24**
- [x] Define editing tools / process **✅2023-06-06 we will use the same stack we are documenting! i.e. MGF (markdown, github, flowershow)**
- [x] ➕2023-06-06 Review and tidy existing epic https://github.com/datopian/makeitmarkdown/issues/1 **✅2023-06-06 split out job stories task, tidied up acceptance and tasks**
- [x] Outline purpose of consolidated guide and define acceptance **✅2023-06-06 good enough for now. see SCQA above + purpose and principles in https://github.com/datopian/portaljs/discussions/927 (may need some refinement and consolidation here)**
- [x] Instructions on how to create documentation **✅2023-06-06 see https://github.com/datopian/portaljs/discussions/929**
- [x] #4
- [x] #5
- [x] Decide where we publish **✅2023-12-14 publish on makeitmarkdown**
```

### Content

https://coggle.it/diagram/ZG5bpZ-I6DjyVLxZ/t/editor-guide-latest-this-part-is-initial-2023-5-24-14-01

- [ ] Tutorial for each job story - first skeleton, then flesh out etc as per #929 **💬2023-06-07  topic and skeleton mega coggle - https://coggle.it/diagram/ZG5bpZ-I6DjyVLxZ/t/editor-guide-latest-this-part-is-initial-2023-5-24-14-01** 
- [x] datopian/portaljs#936

### Misc

- [ ] Reference from any other locations e.g. life itself tao, datopian playbook etc
- [ ] Deprecate any existing guides in favour of this if possible

**Comment by rufuspollock** [comment]
## UPDATE: 2023-11-01

- we made a lot of progress on this in June 2023 with (some of the) results published at https://portaljs.org/guide. 
- also clear we need to do better "shaping" of this project to be clearer on what to ship for our given appetite

Current outstanding work

- [ ] [The Guide] Tutorial 3: Collaboration
- [ ] [The Guide] Tutorial 4: Website configurations

### Sketch of the Guide

- Please do Tutorial 1: "Creating your own sandbox website from scratch using markdown and PortalJS/Flowershow"
  - By the end of that you should have achieved / know how to?
    - Markdown ...
    - Create a new blog post
    - Edit a page via the UI ...
- Please do Tutorial 2: "Editing your own website locally with Obsidian"
- Please read Tutorial 3: Collaborating (aka "Git and Collaboration ...")
- Tutorial 4: Website-y stuff e.g. navbars, footers, etc etcc
- Now, read this step-by-step "howto" on how to edit the life itself website

**Comment by rufuspollock** [comment]
Closing via triage (#56): the outcome this epic wanted — a single place where a non-dev editor can autonomously learn to edit sites, build catalogs and grow a knowledge garden — now exists as the [onboarding path](https://wayofmarkdown.com/learn/onboarding) + tutorial series + guides on wayofmarkdown.com. Life Itself-specific editing docs (lifeitself.org particulars) are out of scope for this site and belong with that repo if still needed.
