### ISSUE TITLE
Outstanding tasks to revisit towards the end of the project

### ISSUE THREAD

**Issue by elisapaka** [datopian/makeitmarkdown#20]
An inbox for keeping track of outstanding tasks that are currently paused.

# Acceptance
- [ ] The following tasks have been completed (if still relevant)

# Tasks
- [ ] Remove tutorial content from portaljs site and add a redirect to makeitmarkdown (see final acceptance point [here](https://github.com/datopian/makeitmarkdown/issues/7#))
- [ ] Remove howtos content from portaljs site and add a redirect to makeitmarkdown (see final acceptance point [here](https://github.com/datopian/makeitmarkdown/issues/19))
- [ ] Transfer any images that we have decided to keep from the portaljs repo to makeitmarkdown (see comment [here](https://github.com/datopian/makeitmarkdown/issues/7#issuecomment-1864282988))
- [ ] Remove 'content' folder in [makeitmarkdown repo](https://github.com/datopian/makeitmarkdown/tree/main) and move its contents up a level (see Rufus' comment [here](https://github.com/datopian/makeitmarkdown/pull/17#issuecomment-1866381440)) **2024-01-04 UPDATE: Have asked Ola for help on how to do this without breaking links to contents inside the folders**

**Comment by rufuspollock** [comment]
Closing via triage (#56): the makeitmarkdown-repo tasks are obsolete (repo restructured into wayofmarkdown). The portaljs-side cleanup (remove old tutorial/howto content there, add redirects here) belongs in the portaljs repo — noted in inbox #45 for @rufuspollock to decide.
