### ISSUE TITLE
Editor guide: Review and recommend for integration existing polished documentation

### ISSUE THREAD

**Issue by rufuspollock** [datopian/makeitmarkdown#5]
Review and recommend for integration the existing polished documentation we already have - see list below

## Acceptance

- [x] List what do we already have: url, title and summary **✅2023-10-31 see below**
- [x] What could we integrate? Make recommendations e.g. below ... **✅2023-10-31 ❌ we did not have any recommendations at the time**
- [x] Flag that info for relevant tutorials (in the issue or to team member etc) **✅2023-10-31 ❌ i think we did use some parts plus we published directly some parts**

## Tasks

Review each of these

- [x] https://lifeitself.org/ecosystem/contributors-guide **Title: Guide to editing Life Itself ecosystem - Summary: Detailed guide on editing the ecosystem page on Life Itself. Comprehensive with images to signpost**
- [x] https://web3.lifeitself.org/meta/editing **Title: Editor's guide using Github + Obsidian/code editor - Summary: Guide on editing the Life Itself webpages, including a section for Obsidian/ other code editors**
- [x] Obsidian Tutorial meeting [Recording](https://drive.google.com/file/d/1RLwl-z8nGA9oQOq9nCwpmFp4NkB088Ti/view) and [Transcript](https://docs.google.com/document/d/1ALIAui9ToT-c6M_96fA8eHFfm6dX5x71olEwmlunAaY/edit) **Title: Tutorial for editing with Obsidian - Summary: 1.5 hour video with Rufus and Nathen as well as complementary transcript**
- [x] Adding internal redirects on the website https://www.loom.com/share/ac3876bb390b417f9077a3e052986a44 **Title: Video guide to adding internal redirects on the website - Summary: 2 minutes long**
- [x] link to the video that explains the [Github and Obsidian workflow](https://drive.google.com/file/d/1Ow0RYya8e3JMZhY5cpCYspsZAA1loses/view?usp=sharing) **💬2023-05-24 ⏭️ need access from owner (nathen)**
- [x] ➕2023-06-06 this tutorial about creating a local catalog with obsidian https://github.com/datopian/markdowndb/tree/main/examples/obsidian-dataview **Title: Guide to creating catologues with Obsidian - Summary: Detailed guide with images as signposting to create catalogues, using Harry Potter characters as examples**
- [x] https://datopian.com/playbook/markdown **Title: Information on Markdown - Summary: Short guide to Markdown and the basics to its usage + redirection to more in-depth tutorials**

✅ DONE: Title + Summary for each resource (excluding one with restricted access)

## Recommendations

**Comment by rufuspollock** [comment]
FIXED. (or obsolete now). This was part of the "markdownbased" effort in June 2023.
