### ISSUE TITLE
Migrate issues and content from https://github.com/datopian/markdownbased 

### ISSUE THREAD

**Issue by rufuspollock** [datopian/makeitmarkdown#8]
## Acceptance

- [x] All issues on markdownbased are processed (migrated or deleted etc) **✅2023-12-14 migrated or consolidated into #2**
- [x] Migrate all content **❌2023-12-14 all relevant content is on portaljs site and is therefore part of #7**

Notes

- [x] https://github.com/datopian/markdownbased/issues/4 - github basics **✅2023-12-14 migrated content and remove issue**
- [x] ... many more

## List as of 2023-12-14

![image](https://github.com/datopian/makeitmarkdown/assets/180658/ea5960ac-7ac7-4312-a6a1-a31674616cd8)

**Comment by rufuspollock** [comment]
FIXED.
