### ISSUE TITLE
How to push my Obsidian vault to GitHub?

### ISSUE THREAD

**Issue by olayway** [datopian/makeitmarkdown#9]
## Acceptance
- a how-to explaining the process of publishing an Obsidian vault to a GitHub repo, using GitHub desktop app

```[tasklist]
## Tasks
- [x] An internal video recording showing clear steps for how to push an Obsidian vault to GH **✅2023-12-14 see below**
- [x] step-by-step instructions instead of the video **💬 in [/content/notes/publish-obsidian-vault-to-github.md](https://github.com/datopian/markdownbased/blob/main/content/notes/publish-obsidian-vault-to-github.md)**
- [ ] draft the howto
```

## Internal video

```[tasklist]
## Tasks
- [x] record the video **Ola & Catherine on 2023-06-09; links in the notes below**
- [x] decide what's easier - using git cli or GitHub desktop app and use that in the howto **💬 GitHub desktop app**
- [ ] @olayway to review the video and figure out some of the blockers we stumbled upon
- [ ] re-record the video with clear steps
```

## Notes

We have a first attempt, so we know what are the pain points

https://drive.google.com/file/d/1uHWC5KuzkdcQQbra1IULmww-SNJsWpv2/view
https://drive.google.com/file/d/1j1VpRrsJcyo6N0D3d7KyflEp-7Rp-RQz/view

Covers:
- creating a new empty repository on GH
- initializing GH repo in the local folder with notes (e.g. vault)
- pushing to the remote repo

**Comment by rufuspollock** [comment]
Done: [How to push an Obsidian vault to GitHub](https://wayofmarkdown.com/learn/howtos/publish-obsidian-vault-to-github) is live (uses GitHub Desktop as decided here). Closing via triage (#56).
